### PR TITLE
Smart weights

### PR DESCRIPTION
**Pull request by EndymionJkb**
Changes proposed in this pull request:
- Change all weight inputs to percentages for clarity
- Limit resolution/max weight for smart pools with canChangeWeights to avoid pokeWeight issues
- Remove unused components

### CODE REVIEW

**Comment by bonustrack** [comment]
> Change all weight inputs to percentages for clarity  

I'm not too fan of changing this, i think it's better if we let the user input any number and give him little room for mistake, the only thing we need to check is if it's a number and if the % is not less than 2% or more than 98%, but we could have someone that type 1000/2000 or 1/5. It will make hard for user to type an invalid weight and should make his experience smoother. Also i wouldn't show "Denorm" column, i think it's confusing for the user what is it, i would rather show the % same as before. 

> Limit resolution/max weight for smart pools with canChangeWeights to avoid pokeWeight issues

Your changes is adding a lot of complexity in the code just to solve the max weight issue, it's also touching on Shared pool weights calculation. Can't we just format this array of weights to fit for the max weight: https://github.com/balancer-labs/pool-management-vue/blob/1f51292dfc79eed673dba6ff0bac00cb45880bb8/src/views/Create.vue#L495 It would be simpler and no touch on the shared pool creation.

**Comment by EndymionJkb** [comment]
Well, let me explain my thinking and intent. (Apologies for length again!) The complexity limits resolution for smart pools to avoid contracts getting stuck calling pokeWeights - this is a big/common problem we need to fix.

The current code is confusing to me, because the input can be either denorm or percentages - but you can't enter 49/1, so it's not truly both, but a muddled mix of the two.

What I'm proposing *should* actually be cleaner and easier to validate, if done properly (so I might need help doing it right).

1) All input is strictly percentages
2) Individual weight validations: all use encapsulated min/max functions - no hard-coded magic numbers in views
3) Validation of the total: always 100
4) There are only two cases, and one variable; everything else is computed. If it's a smart pool with canChangeWeights enabled, the max denorm is 25. denorm range is therefore 1-24, resolution 4% (4%-96%). If it's a shared pool, or a smart pool with canChangeWeights disabled, it reverts to current behavior - max denorm is the core pool default of 50, so range is 1-49, 2% resolution, (2%-98%)

>Can't we just format this array of weights to fit for the max weight
Yes, that what I believe I'm doing.

Because all inputs are percentages, when we call the contract, we can compute denorms (= "fit for max weight") as:
denorm_output = pct_input / (100/max_denorm)

There is a little complexity because we need to handle "legacy" denorm values, or pools that weren't created through the GUI, and might have *any* valid denorm weights (like 1,1 or 5,13). So it calculates the "incoming" percentages based on the actual denorm values, and the "outgoing" denorms based on the new scheme.

This code lets us "fix" stuck pools with one click. Consider the Bankless "stuck" pool, with weights 45/5. It would compute 90%/10% "old weights" from 45/5. It would recognize that it's a smart pool with changeWeights, so 90%/10% outgoing would be 22.5/2.5. Just click confirm, and it would change the weights from 45/5 -> 22.5/2.5 over 10 blocks. No arb opportunity, guaranteed to work because both are going down. This fixes the poke stall. (I'm mainly displaying denorms to show that it works/is doing something in this case.)

Then they could update weights gradually *again* to flip from 90/10 -> 10/90. This time, incoming weights are 22.5/2.5, outgoing weights are 2.5/22.5 - no poke problem

**Comment by EndymionJkb** [comment]
I actually like this better now - the original version was muddled: you could type in either denorms or percentages - but not exactly. You couldn't enter some valid denorm values, like 49/1. Now you can enter any number, including 49/1, or percentage values, or any arbitrary numbers. It will compute the relative percentages, then use those to compute the denorms, based on the computed total (50 if shared/constant weight pool, 25 if smart pool with canChangeWeights).

I thought of a use case for entering large numbers - it allows arbitrary precision in setting weights. Say you want to very precisely adjust weights, to 6 decimal places (e.g., to compensate for impermanent loss) - you can now do it. So this is the most flexible and least error prone: you can enter denorms, or percentages, or large numbers to increase the precision (e.g., 500,002/499998), and everything works. Plus it solves the pokeWeights getting stuck problem

**Comment by bonustrack** [comment]
Thank you for the explanations, some suggestions:
- When there is an error, it's better if we use red color on the input and not on the percentage column to make it more obvious that the user need to change these fields.
image
- Can you use `_num(number, 'percent')` on percent column? This way it will add the "%" sign
- For some reason smart pool creation is not triggered on Metamask when i use this params:
image
Can you reproduce this issue?

**Comment by EndymionJkb** [comment]
Ok; fixed the two issues (plus added more error checking). I can't reproduce your error
Screen Shot 2020-11-09 at 3 33 36 PM
Screen Shot 2020-11-09 at 3 33 25 PM

**Comment by bonustrack** [comment]
I still can reproduce the issue, for some reason i'm not able to create a smart pool with this setup (tried on Kovan)
image
```
Create smart pool 0xe8C178B4927C8D9d053Ce40B33B592E41f798A75 ["BActions","0xeACBe91fE3F8eF6086027AEC0127De982205b1Aa","createSmartPool",["0x53265f0e014995363AE54DAd7059c018BaDbcD74","0x8f7F78080219d4066A8036ccD30D588B416a40DB",{"poolTokenSymbol":"TEST7","poolTokenName":"Test 7","constituentTokens":["0xd0A1E359811322d97991E03f863a0C30C2cF029C","0xef13C0c8abcaf5767160018d268f9697aE4f5375"],"tokenBalances":["9090909090909065","366579513394023"],"tokenWeights":["627000000000000000000","27500000000000000000"],"swapFee":"1500000000000000"},{"initialSupply":"100000000000000000000","minimumWeightChangeBlockPeriod":"10","addTokenTimeLockInBlocks":"10"},{"canChangeSwapFee":true,"canPauseSwapping":true,"canChangeWeights":true,"canAddRemoveTokens":true,"canWhitelistLPs":true,"canChangeCap":true}],{}]
```
I got this error, before seeing Metamask
image

Also i noticed that when i set only 1 weight the tooltip will show "NaN"
image
I feel that in this tooltip it's not obvious what the number is, there should be a better way to show it, or we could not show it for not confuse user.

**Comment by EndymionJkb** [comment]
Ok; I believe I fixed the NaN tooltip (and I added Denorm to explain it). In some edge cases (like fixing a stuck pokeWeights pool) it's important to be able to see it to know it's working.

I will try the pool creation again. The same pool create works on develop and not this branch? It's not broken overall somehow is it?

**Comment by EndymionJkb** [comment]
Ok; found one big issue - the code in broadcast was also calculating weights! Calculated all weights in Create, and just passed them through into broadcast. This is a lot closer. Now I'm having trouble with shared pools:

This works on develop and not smart_weights - *identical* parameters, so I'm not sure what's wrong.
To get these, weights are 95.798319327731,4.201680672268908
Same numbers as 1254,55. Smart pool works; shared pool doesn't.

Create shared pool 0xF489390D0D33C0335f688e39a56fC8B9a265BBd4 ["BActions","0xeACBe91fE3F8eF6086027AEC0127De982205b1Aa","create",["0x8f7F78080219d4066A8036ccD30D588B416a40DB",["0x1528F3FCc26d13F7079325Fb78D9442607781c8C","0x2F375e94FC336Cdec2Dc0cCB5277FE59CBf1cAe5"],["22756999199999975646","1000000"],["47899159663865500000","2100840336134454000"],"1500000000000000",true],{}] broadcast.ts:282

**Comment by bonustrack** [comment]
@EndymionJkb Overall seem to be working well yes. It's just the shared pools, i've tried few combinaison of weights and some are working some not without clear logic, the underlying weight numbers aren't changing much that's strange. 

When creating a smart pool the final weights aren't the same as a shared pool, can't you use the smart pool weight calculation on shared pool too?

**Comment by EndymionJkb** [comment]
> When creating a smart pool the final weights aren't the same as a shared pool, can't you use the smart pool weight calculation on shared pool too?

This is the part that fixes the "stuck pokeWeights" problem. If you don't have canChangeWeights enabled on the smart pool, it will give the exact same numbers for shared and smart pools - and same as before; max of 50, divide by 2. When you have a smart pool with canChangeWeights - to avoid pokeWeights getting stuck - it uses max of 25, divide by 4. So weights will be 1/2 what the shared pool weights would be

**Comment by EndymionJkb** [comment]
So that's the weird thing. Shared pools should do the exact same thing they did before (= same weight outputs for same input numbers). The only difference is you can now enter a wider range of numbers now, where previously you were limited to 98/2

**Comment by bonustrack** [comment]
Ok i see thanks. Did you ever tried on Etherscan to see if it work with the same arguments?

**Comment by EndymionJkb** [comment]
> Ok i see thanks. Did you ever tried on Etherscan to see if it work with the same arguments?

Yes: it is going over the max weight somehow (even though in a calculator, it's exactly 50)
https://kovan.etherscan.io/tx/0x6d722071e00e526b242c195f985b8f0ff58bf6a52a82a127c9d8ff2fa10cb2e9

So allowing high precision must be leading to occasional rounding errors.

**Review by bonustrack — APPROVED** [review]
I tried few different setup and was not able to reproduce the previous error. It seem to be working well by now.

**Review by Destiner — APPROVED** [review]
Did some testing, looks good 👍

**Pull request merged**
