### PR TITLE
Add PieDAO Defi++ pool

### PR DESCRIPTION
**Pull request by EndymionJkb**
Changes proposed in this pull request:
- Add new PieDAO Defi++ Pool

### CODE REVIEW

**Comment by arafat877** [comment]
Hello, what's this project is about please ???

**Comment by EndymionJkb** [comment]
> Hello, what's this project is about please ???

It's just the latest PieDAO pool - we already have all the others (USD++, BTC++, Defi+L, Defi+S)
https://pools.piedao.org/

**Comment by arafat877** [comment]
Can I get involved in this project ???

**Review by bonustrack — APPROVED** [review]
Looks good!

**Comment by arafat877** [comment]
So any place inside your development team ?

Le jeu. 5 nov. 2020 à 06:55, EndymionJkb <notifications@github.com> a
écrit :

**Pull request merged**
