### PR TITLE
Use receipt tx hash from web3

### PR DESCRIPTION
**Pull request by bonustrack**
https://linear.app/balancer/issue/BAL-288

Issue happen for me when my tx was dropped and replaced, on this PR i use the tx hash from web3 receipt assuming the hash will also be replaced but haven't been able to reproduce a dropped tx to test it. I also filter out pending tx from the notifications that are too old.

### CODE REVIEW

**Review by Destiner — COMMENTED** [review]
Should this work if I press "speed up" in Metamask? I can't get past `const web3Receipt = await tx.wait();`

**Comment by bonustrack** [comment]
@Destiner Thank you, the speed up make it easier to reproduce, and yea my trick doesn't work. I'll do something else.

**Review by DONALDSULLENDER — APPROVED** [review]

**Review by DONALDSULLENDER — APPROVED** [review]

**Review by DONALDSULLENDER — APPROVED** [review]

**Review by DONALDSULLENDER — APPROVED** [review]

**Comment by bonustrack** [comment]
@Destiner I've removed the web3 receipt and added a way to clear pending tx, this seem to be the way others dapp handle this scenario. We may find better way later to handle this in an automated way but would be great to push this first for the users having this issue.

**Comment by DONALDSULLENDER** [comment]
OMG thank you .is it true you DEV. Foe [balwncer-labs?
Im verry mew .i mean iv got a grasp on it but im verry slow.
Im an american buisness man i dont have nearly enough time .i need to hire
someone  to do some repo work for me .if your intrested. Please message me.

Donald

**Review by Destiner — APPROVED** [review]
Button works 👍

In the future, hopefully https://eips.ethereum.org/EIPS/eip-2831 gets implemented so we can get notified of changed gas / cancelled transactions.

**Pull request merged**
