### PR TITLE
Padlock + pool creation confirmation modal

### PR DESCRIPTION
**Pull request by Destiner**

### CODE REVIEW

**Comment by bonustrack** [comment]
@Destiner Any reason to store SVG files? How did you generated them? If you want to add an icon i can give you access to the Iconfont project.

**Comment by Destiner** [comment]
@bonustrack I used this one https://www.npmjs.com/package/icon-font-generator. We can use another one if you want. SVGs are there so anyone can update icon set.

**Comment by bonustrack** [comment]
@Destiner Alright, i'm used to iconfont but i will give a try to `icon-font-generator`, i'm not sure contributor will add SVGs but i'd prefer if we don't rely on 3p service. Can you add the pkg in devDependencies?

**Comment by Destiner** [comment]
Yeah by "anyone" I mostly mean our team.

Added package and `generate-icons` script.

**Pull request merged**
