### PR TITLE
Remove coingecko pricing

### PR DESCRIPTION
**Pull request by bonustrack**
Remove coingecko pricing, keep only in pool creation for unknown tokens

### CODE REVIEW

**Comment by bonustrack** [comment]
@Destiner I've fast pushed this fix cuz there is downtime now with Coingecko that were breaking the site. You may want to review this PR, if you see some issue i will implement change in another PR.

**Comment by Destiner** [comment]
@bonustrack  Looks good for now 👍🏻. In the future we want to use subgraph price as a backup only, some assets (e.g. ANJ) are mispriced by ~10%.

**Comment by ping789** [comment]
Isn't because its traded on Balancer at 10% difference? I think in the future we really dont want to rely on Coingecko.

**Comment by bonustrack** [comment]
@Destiner Isn't ANJ mispriced just because it's traded at a different price on Balancer? If it's a problem on the subgraph i can fix it. If it's just because price is different on Balancer protocol that must happen when liquidity is low, we can show warning when this happen. For the future i'd rather target the ultimate solution, and to me 3p dependancy is a terrible solution.

**Comment by Destiner** [comment]
I think mispriced tokens are mostly new/illiquid ones. The problem is that when we list new tokens, they are almost always very illiquid so the price might be off a lot. This is really bad for creating new pools. If we can tell whether the price is off and show a warning that would be better.

Regarding third-party dependencies: I'd like to avoid them as well, but subgraph is no different in this regard. It can fail as well. We have to use coingecko for custom tokens anyway, so I don't see much difference.

I think a good long-term solution is to have a fallback/backup for all the data that we get externally.

**Pull request merged**
