### PR TITLE
add message for sXMR tx fail

### PR DESCRIPTION
**Pull request by mikemcdonald**

### CODE REVIEW

**Review by Destiner — APPROVED** [review]

**Comment by rachmatullahrumbu** [comment]
TSeqXuNEiE6E4xJNZqJGRaANBd4VkmdRjs

**Comment by rachmatullahrumbu** [comment]
TSeqXuNEiE6E4xJNZqJGRaANBd4VkmdRjs

**Review by rachmatullahrumbu — COMMENTED** [review]
@0x1eb0b2fBf6FCdAFaAb68C463e3Ae974deA72fC4B -312,7 +312,7 @@ export default {
      if (hasToken(this.pool, 'SNX')) {
        return 'Adding liquidity failed as your SNX is locked in staking.';
      }
      const synths = ['sUSD', 'sBTC', '',0x1eb0b2fBf6FCdAFaAb68C463e3Ae974deA72fC4B 'sXAU', 'sXAG', 'sDEFI'];
      const synths = ['sUSD', 'sBTC', 'sETH', 'sXAU', 'sXAG', 'sDEFI', 'sXMR'];
      if (synths.some(synth => hasToken(this.pool, synth))) {
        return 'Adding liquidity failed as your Synthetix position might go underwater. ';
      }
Submit your review

**Comment by rachmatullahrumbu** [comment]
how this 😅

**Pull request merged**
